### ISSUE TITLE
Running ERROR with my own video

### ISSUE THREAD

**Issue by YibinWu** [ericlavigne/CarND-Detect-Lane-Lines-And-Vehicles#3]
hello，i am using the program to process my own videos which are already resize to 1280*720,and error below is appearing.
`
  File "C:\Users\10401\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity`
i am not familiar with python.So why it appears and how  can i solve the problem?

**Comment by yanzhang0417** [comment]
Same here. When I was processing the challenge_video, I got the same error with you. Did you solve it?

**Comment by YibinWu** [comment]
No,I did not.If you know how to solve it please share it here.thanks!

**Comment by ericlavigne** [comment]
Did you already run this code successfully on the original video before making changes?

Also, what was the full error message? Error messages are usually at least 10 lines long, and the rest of the message is helpful for determining what went wrong.

**Comment by srirambadri** [comment]
Hi,

I tried using the original video and the code works fine. But like the others above when I try my own video the program crashes with the following error:
`OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "main.py", line 529, in <module>
    main()
  File "main.py", line 526, in main
    process_video('new_video.mp4', 'output_images/videos/new_video.mp4', lane_model, car_model, calibration)
  File "main.py", line 476, in process_video
    clip_out = clip_in.fl_image(processor.process_image)
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 514, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/Clip.py", line 137, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 669, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/Clip.py", line 137, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/home/sriram/.virtualenvs/new/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 514, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "main.py", line 448, in process_image
    markings = image_to_prediction(undistorted, self.lane_model, lane_settings)
  File "main.py", line 223, in image_to_prediction
    model_input = preprocess_input_image(img,opt)[None, :, :, :]
  File "main.py", line 141, in preprocess_input_image
    img = crop_scale_white_balance(img,opt)
  File "main.py", line 132, in crop_scale_white_balance
    img = scale_white_balance(img,opt)
  File "main.py", line 118, in scale_white_balance
    interpolation=cv2.INTER_AREA)
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
`
If the input size is the problem, I checked the sample video size 1280x720. That's the same size I'm suing for my own video.

FYI: I'm not using a GPU
